INSERT INTO `elmundode`.`usuario` (`idUsuario`, `nombreUsuario`, `apellidosUsuario`, `email`, `pass`, `rol`) VALUES (NULL, 'Leticia', 'Pintor Montero', 'leticia@hola.com', 'e8dc4081b13434b45189a720b77b6818', 'creador'), (NULL, 'Pablo', 'Viqueira Ferrer', 'pablo@hola.com', 'e8dc4081b13434b45189a720b77b6818', 'visitante');

INSERT INTO `elmundode`.`bebe` (`idBebe`, `nombreBebe`, `apellidosBebe`, `fechaNacimiento`, `horaNacimiento`, `lugarNacimiento`, `ciudadNacimiento`, `grupoSanguineo`, `imgNacimiento`, `dedicatoriaBebe`, `idUsuario`) VALUES (NULL, 'Mercedes', 'Viqueira Pintor', '2020-06-22', '11:30:00', 'Hospital Materno Infantil', 'A Coru&ntilde;a', 'AB +', NULL, 'Naciste un d&iacute;a soleado de verano. Ten&iacute;amos todo preparado para disfrutar de la m&aacute;gica noche de San Juan una casa rural en compa&ntilde;&iacute;a de tus t&iacute;os, Mar&iacute;a y Pedro, y tus primos, Tom&aacute;s y Teo.\r\nLlegaste por sorpresa dos semanas antes de la fecha. Nos desbarataste los planes. &iexcl;Ni canastilla preparada ten&iacute;amos! Pero, definitivamente, fue el d&iacute;a m&aacute;s m&aacute;gico de nuestra vida :)', '1'), (NULL, 'Marcos', 'Fuente Farelo', '2015-12-23', '23:59:00', 'Hospital Materno Infantil', 'A Coru&ntilde;a', 'B -', NULL, 'Fuiste nuestro regalo de Navidad. Llev&aacute;bamos meses con todo preparado, porque ya de aquellas nos hiciste esperar. S&oacute;lo te falt&oacute; gritar &quot;&iexcl;Ya voy!&quot;. \r\nTardaste tanto que nos ingresaron para hacerte salir, y a&uacute;n as&iacute; tardaste dos d&iacute;as m&aacute;s. Menos mal que te importaba recibir tus primeros presentes Navide&ntilde;os ;) Fijo que naciste el 23 y no el 27 para no perd&eacute;rtelos.', '1');

INSERT INTO `elmundode`.`visitas` (`idVisitas`, `idBebe`, `idUsuario`) VALUES (NULL, '1', '2');

INSERT INTO `elmundode`.`progenitor` (`idProgenitor`, `nombreProgenitor`, `apellidosProgenitor`, `tipoProgenitor`, `fechaNProgenitor`, `lugarNProgenitor`, `descripcionProgenitor`, `imgProgenitor`, `idBebe`) VALUES (NULL, 'Leticia', 'Pintor Montero', 'madre', '1986-09-11', 'A Coru&ntilde;a', 'La toxo del grupo que se convirti&oacute; en una besucona con tu llegada.', NULL, '1'), (NULL, 'Milo', 'Viqueira Ferrer', 'padre', '1982-09-15', 'A Coru&ntilde;a', 'Una cabra loca que pis&oacute; el freno y se convirti&oacute; en una tortuga.', NULL, '1');

INSERT INTO `elmundode`.`embarazo` (`idBebe`, `idProgenitor`, `semanasEmbarazo`, `diasEmbarazo`, `kgAumento`, `fechaNoticia`) VALUES ('1', '1', '38', '5', '8.5', '2019-09-17');

INSERT INTO `elmundode`.`dentadura` (`idDentadura`, `idBebe`, `fechaDiente`, `ordenDiente`, `nombreDiente`) VALUES (null, '1', '2020-12-30', '1', 'Incisivo central derecho inferior'), (null, '1', '2021-02-23', '2', 'Incisivo lateral izquierdo inferior');

INSERT INTO `elmundode`.`crecimiento` (`idCrecimiento`, `idBebe`, `fechaDatos`, `altura`, `peso`, `cabeza`) VALUES ( null, '1', '2020-06-21', '50', '3.5', '40'), (null, '1', '2020-08-21', '57', '5', '43'), ( null, '1', '2020-10-21', '61', '7.5', '45'), ( null, '1', '2020-12-21', '67', '8.5', '45'), ( null, '1', '2021-02-21', '70', '9.7', '46'), ( null, '1', '2021-04-21', '73', '10.5', '47');

INSERT INTO `elmundode`.`anecdota` (`idAnecdota`, `idBebe`, `fechaAnecdota`, `nombreAnecdota`, `lugarAnecdota`, `descripcionAnecdota`, `extraAnecdota`, `tipoExtra`) VALUES ( null, '1', '2020-09-16', 'Adi&oacute;s c&oacute;licos', 'Hogar, dulce hogar', 'Fue el primer d&iacute;a que no te toc&oacute; sufrir por los famosos c&oacute;licos del lactante y la primera vez que de las 3 a las 4 de la ma&ntilde;ana fue una hora feliz y no de llanto.', null, NULL), ( null, '1', '2021-04-13', 'Primera palabra', 'Casa de los abuelos', 'Pese a que todo el mundo cuenta que lo primero que dice un beb&eacute; es \'pap&aacute;\', t&uacute; fuiste a contracorriente y dijiste \'mam&aacute;\'.', NULL, NULL), ( null, '1', '2021-09-17', 'Primera profe prefe', 'Guarder&iacute;a', 'La primera profesora favorita que tuviste fue Ana. &iquest;Te acuerdas? Morena, de pelo rizo y con gafas rojas redondas. &iexcl;Te encantaba!', NULL, NULL);